# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True, help_text='session start datetime')),
                ('finish_datetime', models.DateTimeField(auto_now_add=True, help_text='session finish datetime', null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_session', to='quizapi.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='time_of_answer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answered_datetime',
            field=models.DateTimeField(auto_now=True, help_text='datetime when user answered'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
